
-- 주석
-- 실행 alt+x, ctrl+Enter
SELECT * FROM TEST;

SELECT * FROM TEST2;

--EMPLOYEE SCRIPT 실행 후 (테이블 생성 및 데이터 추가 후)
SELECT * FROM EMPLOYEE;

--현재 계정이 가진 모든 테이블 정보 조회
SELECT * FROM TABS;

--SELECT 문
--특정 테이블의 특정 데이터들을 조회하는 명령어
--SELECT 컬럼명[,(컬럼명),(계산식)..] FROM 테이블명

--모든 행, 모든 컬럼 조회
-- 모든 행: 조건이 딱히 없다.
-- 모든 컬럼: *
SELECT * FROM EMPLOYEE;

-- 사원ID와(EMP_ID) 사원명(EMP_NAME), 연락처(PHONE) 조회
-- EMPLOYEE 테이블에서
SELECT EMP_ID, EMP_NAME, PHONE FROM EMPLOYEE;

--WHERE 절
--테이블에서 조건을 만족하는 값을 가진 행을
-- 따로 선택하여 조회하는 조건 절

--부서코드가 'D6'인 사원 정보 모두 조회
SELECT * FROM EMPLOYEE WHERE DEPT_CODE = 'D6';

SELECT EMP_NAME, EMP_NO FROM EMPLOYEE WHERE DEPT_CODE='D6';

-- EMPLOYEE 테이블에서
-- 직급(JOB_CODE)이 'J1'인 사원의
-- 사번(EMP_ID), 사원명(EMP_NAME), 직급코드(JOB_CODE), 부서코드(DEPT_CODE)를 조회하자

SELECT EMP_ID, EMP_NAME, JOB_CODE, DEPT_CODE FROM EMPLOYEE WHERE JOB_CODE='J1'; 

-- EMLOYEE테이블에서
-- 급여(SALARY)가 300만원 이상인 사원의
-- 아이디(EMP_ID) , 이름(EMP_NAME), 직급(JOB_CODE), 급여(SALARY)조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY FROM EMPLOYEE WHERE SALARY>=3000000;

--위와 동일한 정보를 조회하는데
--급여가 300만원 이상이고 직급이 'J3'인 사원 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY FROM EMPLOYEE WHERE SALARY>=3000000 AND JOB_CODE='J3';


DROP TABLE MYBOARD;
DROP SEQUENCE SEQ_MYBOARD;

CREATE SEQUENCE SEQ_MYBOARD NOCACHE;
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(20) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);
INSERT INTO MYBOARD VALUES(SEQ_MYBOARD.NEXTVAL,'관리자','게시판 테스트',
'테스트 중입니다.
1234567890ABCD', SYSDATE);
SELECT * FROM MYBOARD;

INSERT INTO MYBOARD
VALUES(SEQ_MYBOARD.NEXTVAL, '이창진','3교시','배가 고프네..밥먹으로 갑시다.',SYSDATE);

DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD NOCACHE;

CREATE TABLE BOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(SEQ_BOARD.NEXTVAL, '관리자','테스트 중','TEST1234가나다라',SYSDATE);
SELECT * FROM BOARD;

<<<<<<< HEAD
CREATE SEQUENCE SEQ_MVCBOARD NOCACHE; 
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);
=======
SELECT * FROM MYMEMBER;
>>>>>>> b225ece655d703240ab9db12089c24ce84574ac8

INSERT INTO MVCBOARD
VALUES(SEQ_MVCBOARD.NEXTVAL, '관리자','테스트 중','테스트 1234 ABCD','22/02/22');

SELECT * FROM MVCBOARD;
CREATE SEQUENCE SEQ_MYMEMBER NOCACHE;

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(2000),
	MYPHONE VARCHAR2(1000) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN ('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);

INSERT INTO MYMEMBER VALUES(SEQ_MYMEMBER.NEXTVAL,'ADMIN','ADMIN1234','관리자','관리시 관리구 관리동','010-1234-5678','ADMIN@MYMEMBER.COM','Y','ADMIN');
SELECT * FROM MYMEMBER;

CREATE SEQUENCE SEQ_MLPMEMBER NOCACHE;
CREATE TABLE MLPMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL UNIQUE,
	PW VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(500) NOT NULL,
	EMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	PHONE VARCHAR2(1000) NOT NULL UNIQUE
);

INSERT INTO MLPMEMBER VALUES(SEQ_MLPMEMBER.NEXTVAL,'PSE123','PSE1234','홍길동','PSE123@MULTI.COM','010-1234-1234');
SELECT * FROM MLPMEMBER;












