
-- 주석
-- 실행 alt+x, ctrl+Enter
SELECT * FROM TEST;

SELECT * FROM TEST2;

--EMPLOYEE SCRIPT 실행 후 (테이블 생성 및 데이터 추가 후)
SELECT * FROM EMPLOYEE;

--현재 계정이 가진 모든 테이블 정보 조회
SELECT * FROM TABS;

--SELECT 문
--특정 테이블의 특정 데이터들을 조회하는 명령어
--SELECT 컬럼명[,(컬럼명),(계산식)..] FROM 테이블명

--모든 행, 모든 컬럼 조회
-- 모든 행: 조건이 딱히 없다.
-- 모든 컬럼: *
SELECT * FROM EMPLOYEE;

-- 사원ID와(EMP_ID) 사원명(EMP_NAME), 연락처(PHONE) 조회
-- EMPLOYEE 테이블에서
SELECT EMP_ID, EMP_NAME, PHONE FROM EMPLOYEE;

--WHERE 절
--테이블에서 조건을 만족하는 값을 가진 행을
-- 따로 선택하여 조회하는 조건 절

--부서코드가 'D6'인 사원 정보 모두 조회
SELECT * FROM EMPLOYEE WHERE DEPT_CODE = 'D6';

SELECT EMP_NAME, EMP_NO FROM EMPLOYEE WHERE DEPT_CODE='D6';

-- EMPLOYEE 테이블에서
-- 직급(JOB_CODE)이 'J1'인 사원의
-- 사번(EMP_ID), 사원명(EMP_NAME), 직급코드(JOB_CODE), 부서코드(DEPT_CODE)를 조회하자

SELECT EMP_ID, EMP_NAME, JOB_CODE, DEPT_CODE FROM EMPLOYEE WHERE JOB_CODE='J1'; 

-- EMLOYEE테이블에서
-- 급여(SALARY)가 300만원 이상인 사원의
-- 아이디(EMP_ID) , 이름(EMP_NAME), 직급(JOB_CODE), 급여(SALARY)조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY FROM EMPLOYEE WHERE SALARY>=3000000;

--위와 동일한 정보를 조회하는데
--급여가 300만원 이상이고 직급이 'J3'인 사원 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY FROM EMPLOYEE WHERE SALARY>=3000000 AND JOB_CODE='J3';


DROP TABLE MYBOARD;
DROP SEQUENCE SEQ_MYBOARD;

CREATE SEQUENCE SEQ_MYBOARD NOCACHE;
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(20) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);
INSERT INTO MYBOARD VALUES(SEQ_MYBOARD.NEXTVAL,'관리자','게시판 테스트',
'테스트 중입니다.
1234567890ABCD', SYSDATE);
SELECT * FROM MYBOARD;

INSERT INTO MYBOARD
VALUES(SEQ_MYBOARD.NEXTVAL, '이창진','3교시','배가 고프네..밥먹으로 갑시다.',SYSDATE);

DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD NOCACHE;

CREATE TABLE BOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(SEQ_BOARD.NEXTVAL, '관리자','테스트 중','TEST1234가나다라',SYSDATE);
SELECT * FROM BOARD;

<<<<<<< HEAD
CREATE SEQUENCE SEQ_MVCBOARD NOCACHE; 
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);
=======
SELECT * FROM MYMEMBER;
>>>>>>> b225ece655d703240ab9db12089c24ce84574ac8

INSERT INTO MVCBOARD
VALUES(SEQ_MVCBOARD.NEXTVAL, '관리자','테스트 중','테스트 1234 ABCD','22/02/22');

SELECT * FROM MVCBOARD;
CREATE SEQUENCE SEQ_MYMEMBER NOCACHE;

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(2000),
	MYPHONE VARCHAR2(1000) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN ('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);

INSERT INTO MYMEMBER VALUES(SEQ_MYMEMBER.NEXTVAL,'ADMIN','ADMIN1234','관리자','관리시 관리구 관리동','010-1234-5678','ADMIN@MYMEMBER.COM','Y','ADMIN');
SELECT * FROM MYMEMBER;

<<<<<<< HEAD
CREATE SEQUENCE SEQ_MLPMEMBER NOCACHE;
CREATE TABLE MLPMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL UNIQUE,
	PW VARCHAR2(500) NOT NULL,

	NAME VARCHAR2(500) NOT NULL,
	EMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	PHONE VARCHAR2(1000) NOT NULL UNIQUE
);

INSERT INTO MLPMEMBER VALUES(SEQ_MLPMEMBER.NEXTVAL,'PSE123','PSE1234','홍길동','PSE123@MULTI.COM','010-1234-1234');
SELECT * FROM MLPMEMBER;










=======
DROP TABLE ANSWERBOARD;
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

--글 번호 시퀀스 (PK)
CREATE SEQUENCE BOARDNOSQ NOCACHE; 
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

-- 첫 번째 글 작성
INSERT INTO ANSWERBOARD VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'첫번째 글','1번 글 입니다!!','유저1',SYSDATE);
SELECT * FROM ANSWERBOARD;

INSERT INTO ANSWERBOARD VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'두번째 글','2번 글 입니다!!','유저2',SYSDATE);

--답변글 작성(1번 글의)
--부모(1번글)와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+2,
		'RE:첫번째 글','1번글의 답변 글입니다.','유저2',SYSDATE);
		
	
SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;
		
--세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,'세번째 글','3번 글입니다!!','유저3',SYSDATE)

--답글 작성(두번째 글)
--부모(2번 글)와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
		'RE:두번째 글','2번글의 답변 글입니다.','유저1',SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;
		
		
--답글 작성(NO가 5)
INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+2,
		'RE:RE:두번째 글','2번글의 답변 글의 답변 글','유저2',SYSDATE);

--답변글 작성(두번째글 - NO가 2)
--부모와 같은 GROUPNO에서 
--부모보다 큰 GROUPSQ글들을 GROUPSQ+1
UPDATE ANSWERBOARD SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
  AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;
		
INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
		'RE:두번째 글','2번글의 답변 글 두번째임','유저3',SYSDATE);

--답변 작성(NO-7)
--1. UPDATE
--부모와 같은 GROUPNO이고 부모의 GROUPSQ보다 큰 글들의
--GROUPSQ+1
UPDATE ANSWERBOARD SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
  AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);

--2. INSERT
-- 부모와 같은 GROUPNO, 부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+2,
		'R:RE:두번째글#@#','2번 글 답변 글의 답글','유저2',SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;
		
DROP TABLE MEMBER_JDBC;
DROP SEQUENCE SEQ_MEMBER_JDBC;
CREATE SEQUENCE SEQ_MEMBER_JDBC NOCACHE;
CREATE TABLE MEMBER_JDBC(
	M_NO NUMBER PRIMARY KEY,
	M_NAME VARCHAR2(20) NOT NULL,
	M_AGE NUMBER NOT NULL,
	M_GENDER CHAR(3) CHECK(M_GENDER IN('M','F')) NOT NULL,
	M_LOCATION VARCHAR2(20),
	M_JOB VARCHAR2(20),
	M_TEL VARCHAR2(20),
	M_EMAIL VARCHAR2(20)
);


INSERT INTO MEMBER_JDBC VALUES(SEQ_MEMBER_JDBC.NEXTVAL, '이창진',20,'M','하남','강사',
						'010-1234-5678','leeCJ@LEE.COM');
SELECT * FROM MEMBER_JDBC;

SELECT * FROM MLPMEMBER;

		
INSERT INTO MLPMEMBER VALUES(SEQ_MLPMEMBER.NEXTVAL,'KWS111','KWS123','박상은','kws111@MULTI.COM','010-3333-2222');

SELECT * FROM MLPMEMBER;
DROP SEQUENCE SEQ_MLPMEMBER;
CREATE SEQUENCE SEQ_MLPMEMBER NOCACHE;
DELETE FROM MLPMEMBER;
DROP TABLE MLPMEMBER;
CREATE TABLE MLPMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(2000),
	PW VARCHAR2(2000),
	NAME VARCHAR2(2000),
	EMAIL VARCHAR2(2000),
	PHONE VARCHAR2(2000),
	DEPT VARCHAR2(2000),
	INFO VARCHAR2(2000)
);
INSERT INTO MLPMEMBER VALUES(SEQ_MLPMEMBER.NEXTVAL,'user2','user222','홍길동','user2@multi.com','010-2222-2222','데이터 분석가 부트캠프(파이썬) 3회차','홍길동입니다');
SELECT * FROM MLPMEMBER;


		
		
		
		
		
		